/* ============================================================
   FORM DATA — Áreas de triagem e listas de sintomas
   Eliane Souza Naturopata
============================================================ */

const TRIAGE_AREAS = [
  { value: 'hormonal',   icon: '🌸', title: 'Saúde Hormonal',      sub: 'Menopausa, TPM, andropausa, tireoide', step3Title: 'Saúde <strong>hormonal</strong>' },
  { value: 'digestao',   icon: '🫃', title: 'Digestão & Intestino', sub: 'Intestino, refluxo, gases, intolerâncias', step3Title: 'Digestão <strong>& intestino</strong>' },
  { value: 'sono',       icon: '😴', title: 'Sono & Energia',       sub: 'Insônia, cansaço, fadiga crônica', step3Title: 'Sono <strong>& energia</strong>' },
  { value: 'mental',     icon: '🧠', title: 'Mente & Emoções',      sub: 'Ansiedade, estresse, depressão, burnout', step3Title: 'Mente <strong>& emoções</strong>' },
  { value: 'peso',       icon: '⚖️', title: 'Peso & Metabolismo',   sub: 'Emagrecimento, metabolismo, compulsão', step3Title: 'Peso <strong>& metabolismo</strong>' },
  { value: 'dores',      icon: '🦴', title: 'Dores & Inflamação',   sub: 'Articulações, coluna, enxaqueca', step3Title: 'Dores <strong>& inflamação</strong>' },
  { value: 'pele',       icon: '💆', title: 'Pele & Cabelo',        sub: 'Acne, queda de cabelo, manchas', step3Title: 'Pele <strong>& cabelo</strong>' },
  { value: 'imunidade',  icon: '🛡️', title: 'Imunidade',           sub: 'Alergias, infecções recorrentes, prevenção', step3Title: '<strong>Imunidade</strong> & prevenção' },
];

const SYMPTOM_SETS = {
  hormonal: [
    { id: 'ondas-calor',    icon: '🌡️', name: 'Ondas de calor' },
    { id: 'suor-noturno',   icon: '💧', name: 'Suor noturno' },
    { id: 'insonia',        icon: '🌙', name: 'Insônia' },
    { id: 'irritabilidade', icon: '⚡',  name: 'Irritabilidade' },
    { id: 'ansiedade',      icon: '🌀', name: 'Ansiedade' },
    { id: 'libido',         icon: '💝', name: 'Queda de libido' },
    { id: 'secura',         icon: '🌸', name: 'Secura vaginal' },
    { id: 'cansaco',        icon: '🔋', name: 'Cansaço' },
    { id: 'nevoa',          icon: '🧠', name: 'Névoa mental' },
    { id: 'peso',           icon: '⚖️', name: 'Ganho de peso' },
    { id: 'dores',          icon: '🦴', name: 'Dores articulares' },
    { id: 'cabelo',         icon: '✨', name: 'Queda de cabelo' },
  ],
  digestao: [
    { id: 'constipacao',  icon: '🌿', name: 'Constipação' },
    { id: 'diarreia',     icon: '💧', name: 'Diarreia' },
    { id: 'inchaco',      icon: '🫃', name: 'Inchaço/gases' },
    { id: 'refluxo',      icon: '🔥', name: 'Refluxo' },
    { id: 'azia',         icon: '😮', name: 'Azia' },
    { id: 'nausea',       icon: '🤢', name: 'Náusea' },
    { id: 'dor-abd',      icon: '😣', name: 'Dor abdominal' },
    { id: 'indigestao',   icon: '🍽️', name: 'Indigestão' },
    { id: 'alternancia',  icon: '🔄', name: 'Alternância' },
  ],
  sono: [
    { id: 'insonia',          icon: '🌙', name: 'Insônia' },
    { id: 'dif-adormecer',    icon: '😶', name: 'Difícil adormecer' },
    { id: 'acorda-noite',     icon: '⏰', name: 'Acorda à noite' },
    { id: 'acorda-cansado',   icon: '😴', name: 'Acorda cansado(a)' },
    { id: 'fadiga',           icon: '🔋', name: 'Fadiga diurna' },
    { id: 'sonolencia',       icon: '💤', name: 'Sonolência' },
    { id: 'falta-energia',    icon: '⚡', name: 'Falta de energia' },
    { id: 'irrit-sono',       icon: '😤', name: 'Irritabilidade' },
    { id: 'foco-sono',        icon: '🧠', name: 'Dificuldade de foco' },
  ],
  mental: [
    { id: 'ansiedade-m',  icon: '🌀', name: 'Ansiedade' },
    { id: 'preocupacao',  icon: '😰', name: 'Preocupação excessiva' },
    { id: 'panico',       icon: '⚡', name: 'Ataques de pânico' },
    { id: 'tristeza',     icon: '😔', name: 'Tristeza' },
    { id: 'desanimo',     icon: '💔', name: 'Falta de motivação' },
    { id: 'foco-m',       icon: '🧠', name: 'Dificuldade de foco' },
    { id: 'irrit-m',      icon: '😡', name: 'Irritabilidade' },
    { id: 'burnout',      icon: '🔥', name: 'Burnout' },
    { id: 'insonia-m',    icon: '🌙', name: 'Insônia' },
    { id: 'isolamento',   icon: '🚪', name: 'Isolamento' },
  ],
  peso: [
    { id: 'dif-emagrecer', icon: '⚖️', name: 'Dif. de emagrecer' },
    { id: 'compulsao',     icon: '🍫', name: 'Compulsão alimentar' },
    { id: 'ganho-peso',    icon: '📈', name: 'Ganho de peso' },
    { id: 'retencao',      icon: '💧', name: 'Retenção de líquido' },
    { id: 'fome-exc',      icon: '🍽️', name: 'Fome excessiva' },
    { id: 'doce',          icon: '🍬', name: 'Desejo por doces' },
    { id: 'cansaco-p',     icon: '🔋', name: 'Cansaço' },
    { id: 'inchaco-abd',   icon: '🫃', name: 'Inchaço abdominal' },
    { id: 'gord-abd',      icon: '🔵', name: 'Gordura abdominal' },
  ],
  dores: [
    { id: 'dor-coluna',    icon: '🦴', name: 'Dor na coluna' },
    { id: 'dor-articular', icon: '🦵', name: 'Dores articulares' },
    { id: 'dor-muscular',  icon: '💪', name: 'Dores musculares' },
    { id: 'enxaqueca',     icon: '🤕', name: 'Enxaqueca' },
    { id: 'cefaleia',      icon: '🔨', name: 'Cefaleia' },
    { id: 'rigidez',       icon: '🧊', name: 'Rigidez matinal' },
    { id: 'dor-geral',     icon: '😣', name: 'Dores generalizadas' },
    { id: 'formigamento',  icon: '⚡', name: 'Formigamento' },
    { id: 'fadiga-musc',   icon: '🔋', name: 'Fadiga muscular' },
  ],
  pele: [
    { id: 'acne',       icon: '🔴', name: 'Acne' },
    { id: 'pele-oleosa',icon: '💧', name: 'Pele oleosa' },
    { id: 'pele-seca',  icon: '🏜️', name: 'Pele seca' },
    { id: 'manchas',    icon: '🟤', name: 'Manchas/melasma' },
    { id: 'rosacea',    icon: '🌹', name: 'Rosácea' },
    { id: 'queda-cab',  icon: '✨', name: 'Queda de cabelo' },
    { id: 'cab-fino',   icon: '🪮', name: 'Cabelo fino' },
    { id: 'unhas',      icon: '💅', name: 'Unhas fracas' },
    { id: 'psoriase',   icon: '🔵', name: 'Psoríase/eczema' },
  ],
  imunidade: [
    { id: 'gripes',        icon: '🤧', name: 'Gripes frequentes' },
    { id: 'alergias',      icon: '🌺', name: 'Alergias' },
    { id: 'sinusite',      icon: '👃', name: 'Sinusite/rinite' },
    { id: 'candidose',     icon: '🔵', name: 'Candidíase recorrente' },
    { id: 'herpes',        icon: '⚡', name: 'Herpes recorrente' },
    { id: 'infeccoes',     icon: '🦠', name: 'Infecções recorrentes' },
    { id: 'baixa-energia', icon: '🔋', name: 'Baixa energia' },
    { id: 'cicatrizacao',  icon: '🩹', name: 'Cicatrização lenta' },
    { id: 'autoimune',     icon: '🛡️', name: 'Autoimune' },
  ],
};

const TOTAL_STEPS = 9;
